

export const FETCH_DASHBOARD_DATA_BEGIN = "FETCH_DASHBOARD_DATA_BEGIN";
export const FETCH_DASHBOARD_DATA_FAILURE = "FETCH_DASHBOARD_DATA_FAILURE";
export const FETCH_DASHBOARD_DATA_SUCCESS = "FETCH_DASHBOARD_DATA_SUCCESS";

export const FETCH_LANDING_JSON_DATA_BEGIN = "FETCH_LANDING_JSON_DATA_BEGIN";
export const FETCH_LANDING_JSON_DATA_FAILURE = "FETCH_LANDING_JSON_DATA_FAILURE";
export const FETCH_LANDING_JSON_DATA_SUCCESS = "FETCH_LANDING_JSON_DATA_SUCCESS";

export const FETCH_ABOUT_JSON_DATA_BEGIN = "FETCH_ABOUT_JSON_DATA_BEGIN";
export const FETCH_ABOUT_JSON_DATA_FAILURE = "FETCH_ABOUT_JSON_DATA_FAILURE";
export const FETCH_ABOUT_JSON_DATA_SUCCESS = "FETCH_ABOUT_JSON_DATA_SUCCESS";

export const FETCH_DEMO_JSON_DATA_BEGIN = "FETCH_DEMO_JSON_DATA_BEGIN";
export const FETCH_DEMO_JSON_DATA_FAILURE = "FETCH_DEMO_JSON_DATA_FAILURE";
export const FETCH_DEMO_JSON_DATA_SUCCESS = "FETCH_DEMO_JSON_DATA_SUCCESS";

export const FETCH_CONTACT_JSON_DATA_BEGIN = "FETCH_CONTACT_JSON_DATA_BEGIN";
export const FETCH_CONTACT_JSON_DATA_FAILURE = "FETCH_CONTACT_JSON_DATA_FAILURE";
export const FETCH_CONTACT_JSON_DATA_SUCCESS = "FETCH_CONTACT_JSON_DATA_SUCCESS";

export const FETCH_MENUBAR_JSON_DATA_BEGIN = "FETCH_MENUBAR_JSON_DATA_BEGIN";
export const FETCH_MENUBAR_JSON_DATA_FAILURE = "FETCH_MENUBAR_JSON_DATA_FAILURE";
export const FETCH_MENUBAR_JSON_DATA_SUCCESS = "FETCH_MENUBAR_JSON_DATA_SUCCESS";

export const FETCH_FOOTER_JSON_DATA_BEGIN = "FETCH_FOOTER_JSON_DATA_BEGIN";
export const FETCH_FOOTER_JSON_DATA_FAILURE = "FETCH_FOOTER_JSON_DATA_FAILURE";
export const FETCH_FOOTER_JSON_DATA_SUCCESS = "FETCH_FOOTER_JSON_DATA_SUCCESS";

export const FETCH_USER_JSON_DATA_BEGIN = "FETCH_USER_JSON_DATA_BEGIN";
export const FETCH_USER_DATA_BEGIN = "FETCH_USER_DATA_BEGIN";
export const FETCH_USER_JSON_DATA_FAILURE = "FETCH_USER_JSON_DATA_FAILURE";
export const FETCH_USER_JSON_DATA_SUCCESS = "FETCH_USER_JSON_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";

export const FETCH_AIRCRAFT_JSON_DATA_BEGIN = "FETCH_AIRCRAFT_JSON_DATA_BEGIN";
export const FETCH_AIRCRAFT_JSON_DATA_FAILURE = "FETCH_AIRCRAFT_JSON_DATA_FAILURE";
export const FETCH_AIRCRAFT_JSON_DATA_SUCCESS = "FETCH_AIRCRAFT_JSON_DATA_SUCCESS";
export const FETCH_AIRCRAFT_DATA_FAILURE = "FETCH_AIRCRAFT_DATA_FAILURE";
export const FETCH_AIRCRAFT_DATA_SUCCESS = "FETCH_AIRCRAFT_DATA_SUCCESS";

export const FETCH_PAYMENT_JSON_DATA_BEGIN = "FETCH_PAYMENT_JSON_DATA_BEGIN";
export const FETCH_PAYMENT_JSON_DATA_FAILURE = "FETCH_PAYMENT_JSON_DATA_FAILURE";
export const FETCH_PAYMENT_JSON_DATA_SUCCESS = "FETCH_PAYMENT_JSON_DATA_SUCCESS";
export const FETCH_PAYMENT_DATA_FAILURE = "FETCH_PAYMENT_DATA_FAILURE";
export const FETCH_PAYMENT_DATA_SUCCESS = "FETCH_PAYMENT_DATA_SUCCESS";

export const FETCH_DOCUMENT_JSON_DATA_BEGIN = "FETCH_DOCUMENT_JSON_DATA_BEGIN";
export const FETCH_DOCUMENT_JSON_DATA_FAILURE = "FETCH_DOCUMENT_JSON_DATA_FAILURE";
export const FETCH_DOCUMENT_JSON_DATA_SUCCESS = "FETCH_DOCUMENT_JSON_DATA_SUCCESS";
export const FETCH_DOCUMENT_DATA_BEGIN = "FETCH_DOCUMENT_DATA_BEGIN";
export const FETCH_DOCUMENT_DATA_FAILURE = "FETCH_DOCUMENT_DATA_FAILURE";
export const FETCH_DOCUMENT_DATA_SUCCESS = "FETCH_DOCUMENT_DATA_SUCCESS";

export const FETCH_ACCOUNT_HOME_DATA_BEGIN = "FETCH_ACCOUNT_HOME_DATA_BEGIN";
export const FETCH_ACCOUNT_HOME_DATA_FAILURE = "FETCH_ACCOUNT_HOME_DATA_FAILURE";
export const FETCH_ACCOUNT_HOME_DATA_SUCCESS = "FETCH_ACCOUNT_HOME_DATA_SUCCESS";
export const GET_UPDATE_PROFILE_BEGIN = "GET_UPDATE_PROFILE_BEGIN";
export const GET_UPDATE_PROFILE_FAILURE = "GET_UPDATE_PROFILE_FAILURE";
export const GET_UPDATE_PROFILE_SUCCESS = "GET_UPDATE_PROFILE_SUCCESS";
export const GET_SELECTED_USER = "GET_SELECTED_USER";
export const GET_SELECTED_TAB = "GET_SELECTED_TAB";

export const FETCH_SEARCH_HOME_DATA_BEGIN = "FETCH_SEARCH_HOME_DATA_BEGIN";
export const FETCH_SEARCH_HOME_DATA_FAILURE = "FETCH_SEARCH_HOME_DATA_FAILURE";
export const FETCH_SEARCH_HOME_DATA_SUCCESS = "FETCH_SEARCH_HOME_DATA_SUCCESS";
export const FETCH_SEARCH_USER_DATA_BEGIN = "FETCH_SEARCH_USER_DATA_BEGIN";
export const FETCH_SEARCH_USER_DATA_FAILURE = "FETCH_SEARCH_USER_DATA_FAILURE";
export const FETCH_SEARCH_USER_DATA_SUCCESS = "FETCH_SEARCH_USER_DATA_SUCCESS";
export const FETCH_SEARCH_AIRCRAFT_DATA_BEGIN = "FETCH_SEARCH_AIRCRAFT_DATA_BEGIN";
export const FETCH_SEARCH_AIRCRAFT_DATA_FAILURE = "FETCH_SEARCH_AIRCRAFT_DATA_FAILURE";
export const FETCH_SEARCH_AIRCRAFT_DATA_SUCCESS = "FETCH_SEARCH_AIRCRAFT_DATA_SUCCESS";
export const FETCH_SEARCH_COMPANY_DATA_BEGIN = "FETCH_SEARCH_COMPANY_DATA_BEGIN";
export const FETCH_SEARCH_COMPANY_DATA_FAILURE = "FETCH_SEARCH_COMPANY_DATA_FAILURE";
export const FETCH_SEARCH_COMPANY_DATA_SUCCESS = "FETCH_SEARCH_COMPANY_DATA_SUCCESS";
export const GET_SEARCH_SELECTED_TAB = "GET_SEARCH_SELECTED_TAB";
export const GET_SEARCH_VALUE = "GET_SEARCH_VALUE";
export const GET_SEARCH_SELECTED_USER = "GET_SEARCH_SELECTED_USER";
export const GET_SELECTED_COMPANY = "GET_SELECTED_COMPANY";
export const MOBILE_HEADER_TEXT = "MOBILE_HEADER_TEXT";
export const MOBILE_FAVORITE_FBO="MOBILE_FAVORITE_FBO";

export const FETCH_PROFILE_DATA_BEGIN = "FETCH_PROFILE_DATA_BEGIN";
export const FETCH_PROFILE_DATA_FAILURE = "FETCH_PROFILE_DATA_FAILURE";
export const FETCH_PROFILE_DATA_SUCCESS = "FETCH_PROFILE_DATA_SUCCESS";

export const FETCH_ACCOUNT_COMPANY_DATA_BEGIN = "FETCH_ACCOUNT_COMPANY_DATA_BEGIN";
export const FETCH_ACCOUNT_COMPANY_DATA_FAILURE = "FETCH_ACCOUNT_COMPANY_DATA_FAILURE";
export const FETCH_ACCOUNT_COMPANY_DATA_SUCCESS = "FETCH_ACCOUNT_COMPANY_DATA_SUCCESS";

export const FETCH_ACCOUNT_LOCATION_DATA_BEGIN = "FETCH_ACCOUNT_LOCATION_DATA_BEGIN";
export const FETCH_ACCOUNT_LOCATION_DATA_FAILURE = "FETCH_ACCOUNT_LOCATION_DATA_FAILURE";
export const FETCH_ACCOUNT_LOCATION_DATA_SUCCESS = "FETCH_ACCOUNT_LOCATION_DATA_SUCCESS";

export const FETCH_ACCOUNT_LOCATION_DATA_DATA_BEGIN = "FETCH_ACCOUNT_LOCATION_DATA_DATA_BEGIN";
export const FETCH_ACCOUNT_LOCATION_DATA_DATA_FAILURE = "FETCH_ACCOUNT_LOCATION_DATA_DATA_FAILURE";
export const FETCH_ACCOUNT_LOCATION_DATA_DATA_SUCCESS = "FETCH_ACCOUNT_LOCATION_DATA_DATA_SUCCESS";

export const NOTIFICATION_DATA_BEGIN = "NOTIFICATION_DATA_BEGIN";
export const NOTIFICATION_DATA_FAILURE = "NOTIFICATION_DATA_FAILURE";
export const NOTIFICATION_DATA_SUCCESS = "NOTIFICATION_DATA_SUCCESS";
export const SAVE_NOTIFICATION_FAILURE = "SAVE_NOTIFICATION_FAILURE";
export const SAVE_NOTIFICATION_SUCCESS = "SAVE_NOTIFICATION_SUCCESS";

export const ENROLLMENT_NEW_FAILURE = "ENROLLMENT_NEW_FAILURE";
export const ENROLLMENT_NEW_SUCCESS = "ENROLLMENT_NEW_SUCCESS";
export const ENROLLMENT_PENDING_FAILURE = "ENROLLMENT_PENDING_FAILURE";
export const ENROLLMENT_PENDING_SUCCESS = "ENROLLMENT_PENDING_SUCCESS";
export const ENROLLMENT_COMPLETE_FAILURE = "ENROLLMENT_COMPLETE_FAILURE";
export const ENROLLMENT_COMPLETE_SUCCESS = "ENROLLMENT_COMPLETE_SUCCESS";
export const ONBOARDING_VIEW = "ONBOARDING_VIEW";
export const FETCH_FUEL_PRICE_DATA_BEGIN = "FETCH_FUEL_PRICE_DATA_BEGIN";
export const FETCH_FUEL_PRICE_DATA_FAILURE = "FETCH_FUEL_PRICE_DATA_FAILURE";
export const FETCH_FUEL_PRICE_DATA_SUCCESS = "FETCH_FUEL_PRICE_DATA_SUCCESS";
export const GET_SELECTED_TAB_FUEL_PRICE ="GET_SELECTED_TAB_FUEL_PRICE"

export const FETCH_TAX_FEES_DATA_BEGIN = "FETCH_TAX_FEES_DATA_BEGIN";
export const FETCH_TAX_FEES_DATA_FAILURE = "FETCH_TAX_FEES_DATA_FAILURE";
export const FETCH_TAX_FEES_DATA_SUCCESS = "FETCH_TAX_FEES_DATA_SUCCESS";

export const FETCH_TAX_DATA_BEGIN = "FETCH_TAX_DATA_BEGIN";
export const FETCH_TAX_DATA_FAILURE = "FETCH_TAX_DATA_FAILURE";
export const FETCH_TAX_DATA_SUCCESS = "FETCH_TAX_DATA_SUCCESS";
export const FETCH_TAX_DETAILS_BEGIN = "FETCH_TAX_DETAILS_BEGIN";
export const FETCH_TAX_DETAILS_FAILURE = "FETCH_TAX_DETAILS_FAILURE";
export const FETCH_TAX_DETAILS_SUCCESS = "FETCH_TAX_DETAILS_SUCCESS";
export const GET_TAXHOME_SELECTED_TAB = "GET_TAXHOME_SELECTED_TAB"; 
export const GET_SELECTED_COMPANY_TAX = "GET_SELECTED_COMPANY_TAX";
export const GET_SELECTED_USER_TAX = "GET_SELECTED_USER_TAX";
export const GET_SELECTED_TAB_TAX = "GET_SELECTED_TAB_TAX";

export const FETCH_FEE_DATA_BEGIN = "FETCH_FEE_DATA_BEGIN";
export const FETCH_FEE_DATA_FAILURE = "FETCH_FEE_DATA_FAILURE";
export const FETCH_FEE_DATA_SUCCESS = "FETCH_FEE_DATA_SUCCESS";
export const FETCH_FEE_DETAILS_BEGIN = "FETCH_FEE_DETAILS_BEGIN";
export const FETCH_FEE_DETAILS_FAILURE = "FETCH_FEE_DETAILS_FAILURE";
export const FETCH_FEE_DETAILS_SUCCESS = "FETCH_FEE_DETAILS_SUCCESS";

export const FETCH_ADDITIONALSERVICES_DATA_BEGIN = "FETCH_ADDITIONALSERVICES_DATA_BEGIN";
export const FETCH_ADDITIONALSERVICES_FAILURE = "FETCH_ADDITIONALSERVICES_FAILURE";
export const FETCH_ADDITIONALSERVICES_DATA_SUCCESS = "FETCH_ADDITIONALSERVICES_DATA_SUCCESS";
export const FETCH_ADDITIONALSERVICES_DETAILS_BEGIN = "FETCH_ADDITIONALSERVICES_DETAILS_BEGIN";
export const FETCH_ADDITIONALSERVICES_DETAILS_FAILURE = "FETCH_ADDITIONALSERVICES_DETAILS_FAILURE";
export const FETCH_ADDITIONALSERVICES_DETAILS_SUCCESS = "FETCH_ADDITIONALSERVICES_DETAILS_SUCCESS";
export const GET_ADDITIONALSERVICESHOME_SELECTED_TAB = "GET_ADDITIONALSERVICESHOME_SELECTED_TAB";
export const FETCH_DISCOUNT_DATA_BEGIN = "FETCH_DISCOUNT_DATA_BEGIN";
export const FETCH_DISCOUNT_DATA_FAILURE = "FETCH_DISCOUNT_DATA_FAILURE";
export const FETCH_DISCOUNT_DATA_SUCCESS = "FETCH_DISCOUNT_DATA_SUCCESS";
export const FETCH_DISCOUNT_JSON_DATA_BEGIN = "FETCH_DISCOUNT_JSON_DATA_BEGIN";
export const FETCH_DISCOUNT_JSON_DATA_SUCCESS = "FETCH_DISCOUNT_JSON_DATA_SUCCESS";
export const FETCH_DISCOUNT_JSON_DATA_FAILURE= "FETCH_DISCOUNT_JSON_DATA_FAILURE";
export const GET_DISCOUNT_SELECTED_COMPANY = "GET_DISCOUNT_SELECTED_COMPANY";
export const FETCH_TAIL_NUMBERS_FAILURE = "FETCH_TAIL_NUMBERS_FAILURE";
export const FETCH_TAIL_NUMBERS_SUCCESS = "FETCH_TAIL_NUMBERS_SUCCESS";
export const FETCH_BULK_UPLOAD_JSON_DATA_SUCCESS = "FETCH_BULK_UPLOAD_JSON_DATA_SUCCESS";
export const FETCH_BULK_UPLOAD_JSON_DATA_FAILURE ="FETCH_BULK_UPLOAD_JSON_DATA_FAILURE";
export const FETCH_OPERATOR_FOR_BULK_UPLOAD_SUCCESS = "FETCH_OPERATOR_FOR_BULK_UPLOAD_SUCCESS";
export const FETCH_OPERATOR_FOR_BULK_UPLOAD_FAILURE = "FETCH_OPERATOR_FOR_BULK_UPLOAD_FAILURE";

export const FETCH_LOGIN_DATA_SUCCESS = "FETCH_LOGIN_DATA_SUCCESS";
export const FETCH_LOGIN_DATA_FAILURE = "FETCH_LOGIN_DATA_FAILURE";
export const FETCH_LOGIN_DATA_BEGIN = "FETCH_LOGIN_DATA_BEGIN";
export const FETCH_LOGIN_DETAILS = "FETCH_LOGIN_DETAILS";
export const FETCH_CSRF_TOKEN = "FETCH_CSRF_TOKEN";
export const GET_LOGGEDIN_ACCESS_LEVEL = "GET_LOGGEDIN_ACCESS_LEVEL";

/* Common action Types*/
export const ENABLE_POPUP = "ENABLE_POPUP";
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const LOGGED_IN_USERTYPE = "LOGGED_IN_USERTYPE";
export const LOGGED_IN_FIRSTNAME = "LOGGED_IN_FIRSTNAME";
export const LOGGED_IN_COMPANY = "LOGGED_IN_COMPANY";

/* add new fuel*/

export const FETCH_ADD_NEW_FUEL_DATA_BEGIN = "FETCH_ADD_NEW_FUEL_DATA_BEGIN";
export const FETCH_ADD_NEW_FUEL_DATA_FAILURE = "FETCH_ADD_NEW_FUEL_DATA_FAILURE";
export const FETCH_ADD_NEW_FUEL_DATA_SUCCESS = "FETCH_ADD_NEW_FUEL_DATA_SUCCESS";

export const FETCH_ADD_NEW_FUEL_DATA_DATA_BEGIN = "FETCH_ADD_NEW_FUEL_DATA_DATA_BEGIN";
export const FETCH_ADD_NEW_FUEL_DATA_DATA_FAILURE = "FETCH_ADD_NEW_FUEL_DATA_DATA_FAILURE";
export const FETCH_ADD_NEW_FUEL_DATA_DATA_SUCCESS = "FETCH_ADD_NEW_FUEL_DATA_DATA_SUCCESS";
export const GET_SELECTED_FUEL_USER ="GET_SELECTED_FUEL_USER"

export const FETCH_FUEL_TIRE_DATA_BEGIN = "FETCH_FUEL_TIRE_DATA_BEGIN";
export const FETCH_FUEL_TIRE_DATA_FAILURE = "FETCH_FUEL_TIRE_DATA_FAILURE";
export const FETCH_FUEL_TIRE_DATA_SUCCESS = "FETCH_FUEL_TIRE_DATA_SUCCESS";
export const CLIENT_SCREEN = "CLIENT_SCREEN";

export const FETCH_SEARCHFUEL_JSON_DATA_BEGIN = "FETCH_SEARCHFUEL_JSON_DATA_BEGIN";
export const FETCH_SEARCHFUEL_JSON_DATA_FAILURE = "FETCH_SEARCHFUEL_JSON_DATA_FAILURE";
export const FETCH_SEARCHFUEL_JSON_DATA_SUCCESS = "FETCH_SEARCHFUEL_JSON_DATA_SUCCESS";
export const FETCH_SEARCHFUEL_DATA_FAILURE = "FETCH_SEARCHFUEL_DATA_FAILURE";
export const FETCH_SEARCHFUEL_DATA_SUCCESS = "FETCH_SEARCHFUEL_DATA_SUCCESS";
export const FETCH_SEARCHFUEL_RESULT_BEGIN = "FETCH_SEARCHFUEL_RESULT_BEGIN";
export const FETCH_SEARCHFUEL_RESULT_FAILURE = "FETCH_SEARCHFUEL_RESULT_FAILURE";
export const FETCH_SEARCHFUEL_RESULT_SUCCESS = "FETCH_SEARCHFUEL_RESULT_SUCCESS";
export const FETCH_PREFFEREDFBO_RESULT_BEGIN = "FETCH_PREFFEREDFBO_RESULT_BEGIN";
export const FETCH_PREFFEREDFBO_RESULT_FAILURE = "FETCH_PREFFEREDFBO_RESULT_FAILURE";
export const FETCH_PREFFEREDFBO_RESULT_SUCCESS = "FETCH_PREFFEREDFBO_RESULT_SUCCESS";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS"
export const GET_MOBILE_ORDER_DETAILS = "GET_MOBILE_ORDER_DETAILS"

export const FETCH_FUEL_ACTIVE_DATA_BEGIN = "FETCH_FUEL_ACTIVE_DATA_BEGIN";
export const FETCH_FUEL_ACTIVE_DATA_FAILURE = "FETCH_FUEL_ACTIVE_DATA_FAILURE";
export const FETCH_FUEL_ACTIVE_DATA_SUCCESS = "FETCH_FUEL_ACTIVE_DATA_SUCCESS";

export const FETCH_SAVE_FUEL_TIRE_DATA_BEGIN = "FETCH_SAVE_FUEL_TIRE_DATA_BEGIN";
export const FETCH_SAVE_FUEL_TIRE_DATA_FAILURE = "FETCH_SAVE_FUEL_TIRE_DATA_FAILURE";
export const FETCH_SAVE_FUEL_TIRE_DATA_SUCCESS = "FETCH_SAVE_FUEL_TIRE_DATA_SUCCESS";

export const FETCH_DEFAULT_TIRE_DATA_BEGIN = "FETCH_DEFAULT_TIRE_DATA_BEGIN";
export const FETCH_DEFAULT_TIRE_DATA_FAILURE = "FETCH_DEFAULT_TIRE_DATA_FAILURE";
export const FETCH_DEFAULT_TIRE_DATA_SUCCESS = "FETCH_DEFAULT_TIRE_DATA_SUCCESS";

export const FETCH_FUEL_ARCHIVE_DATA_BEGIN = "FETCH_FUEL_ARCHIVE_DATA_BEGIN";
export const FETCH_FUEL_ARCHIVE_DATA_FAILURE = "FETCH_FUEL_ARCHIVE_DATA_FAILURE";
export const FETCH_FUEL_ARCHIVE_DATA_SUCCESS = "FETCH_FUEL_ARCHIVE_DATA_SUCCESS";

export const FETCH_ORDER_HOME_JSON_BEGIN = "FETCH_ORDER_HOME_JSON_BEGIN";
export const FETCH_ORDER_HOME_JSON_FAILURE = "FETCH_ORDER_HOME_JSON_FAILURE";
export const FETCH_ORDER_HOME_JSON_SUCCESS = "FETCH_ORDER_HOME_JSON_SUCCESS";
export const SAVE_ORDER_DATA_BEGIN = "SAVE_ORDER_DATA_BEGIN";
export const SAVE_ORDER_DATA_FAILURE = "SAVE_ORDER_DATA_FAILURE";
export const SAVE_ORDER_DATA_SUCCESS = "SAVE_ORDER_DATA_SUCCESS";

export const MULTI_LEG_JSON_BEGIN = "MULTI_LEG_JSON_BEGIN";
export const MULTI_LEG_JSON_FAILURE = "MULTI_LEG_JSON_FAILURE";
export const MULTI_LEG_JSON_SUCCESS = "MULTI_LEG_JSON_SUCCESS";
export const LEG_DATA = "LEG_DATA";
export const FUEL_INFO = "FUEL_INFO";


export const MULTI_LEG_SUMMARY_JSON_BEGIN = "MULTI_LEG_SUMMARY_JSON_BEGIN";
export const MULTI_LEG_SUMMARY_JSON_FAILURE = "MULTI_LEG_SUMMARY_JSON_FAILURE";
export const MULTI_LEG_SUMMARY_JSON_SUCCESS = "MULTI_LEG_SUMMARY_JSON_SUCCESS";

export const FETCH_ORDER_DATA_JSON_BEGIN = "FETCH_ORDER_DATA_JSON_BEGIN";
export const FETCH_ORDER_DATA_JSON_FAILURE = "FETCH_ORDER_DATA_JSON_FAILURE";
export const FETCH_ORDER_DATA_JSON_SUCCESS = "FETCH_ORDER_DATA_JSON_SUCCESS";
export const FETCH_ORDER_VIEW_JSON_BEGIN = "FETCH_ORDER_VIEW_JSON_BEGIN";
export const FETCH_ORDER_VIEW_JSON_FAILURE = "FETCH_ORDER_VIEW_JSON_FAILURE";
export const FETCH_ORDER_VIEW_JSON_SUCCESS = "FETCH_ORDER_VIEW_JSON_SUCCESS";
export const FETCH_ORDER_VIEW_HOME_JSON_BEGIN = "FETCH_ORDER_VIEW_HOME_JSON_BEGIN";
export const FETCH_ORDER_VIEW_HOME_JSON_FAILURE = "FETCH_ORDER_VIEW_HOME_JSON_FAILURE";
export const FETCH_ORDER_VIEW_HOME_JSON_SUCCESS = "FETCH_ORDER_VIEW_HOME_JSON_SUCCESS";
export const IS_MULTILEG = "IS_MULTILEG";
export const ORDER_ID = "ORDER_ID";
export const LEG_LEVEL = "LEG_LEVEL";
export const MULTIPLE_LEG = "MULTIPLE_LEG";
export const IS_SUMMARY = "IS_SUMMARY";
export const EDIT_LEG_DATA = "EDIT_LEG_DATA";
export const IS_EDIT = "IS_EDIT";
export const FROM_LOCATION = "FROM_LOCATION";
export const IS_PRICE_PENDING = "IS_PRICE_PENDING";
export const IS_REORDER = "IS_REORDER";
export const IS_EDIT_SINGLE = "IS_EDIT_SINGLE";
export const IS_EDIT_MULTIPLE = "IS_EDIT_MULTIPLE";
export const IS_ORDER_ACCEPT = "IS_ORDER_ACCEPT";
export const IS_ORDER_CLOSE = "IS_ORDER_CLOSE";
export const IS_PREVIOUS_SCREEN = "IS_PREVIOUS_SCREEN";
export const IS_MULTI_SUMMARY = "IS_MULTI_SUMMARY";
export const IS_MULTI_LEG_PRICE_PENDING = "IS_MULTI_LEG_PRICE_PENDING";

export const FETCH_ORDER_SUMMARY_JSON_BEGIN = "FETCH_ORDER_SUMMARY_JSON_BEGIN";
export const FETCH_ORDER_SUMMARY_JSON_FAILURE = "FETCH_ORDER_SUMMARY_JSON_FAILURE";
export const FETCH_ORDER_SUMMARY_JSON_SUCCESS = "FETCH_ORDER_SUMMARY_JSON_SUCCESS";
export const GET_ALL_LOCATIONS_TAX = "GET_ALL_LOCATIONS_TAX"
export const FETCH_FBO_NAME_SUCCESS = "FETCH_FBO_NAME_SUCCESS"
export const FETCH_FBO_NAME_FAILURE = "FETCH_FBO_NAME_FAILURE"
export const GET_SELECTED_COMPANY_FUEL = "GET_SELECTED_COMPANY_FUEL"

export const DISPUTE_DATA = "DISPUTE_DATA";
export const FETCH_ACTIVE_ORDER_JSON_DATA_BEGIN = "FETCH_ACTIVE_ORDER_JSON_DATA_BEGIN";
export const FETCH_ACTIVE_ORDER_JSON_DATA_FAILURE = "FETCH_ACTIVE_ORDER_JSON_DATA_FAILURE";
export const FETCH_ACTIVE_ORDER_JSON_DATA_SUCCESS = "FETCH_ACTIVE_ORDER_JSON_DATA_SUCCESS";
export const DISPUTE_ORDER_DATA = "DISPUTE_ORDER_DATA"
export const DISPUTE_VIEW_SCREEN = "DISPUTE_VIEW_SCREEN"
export const DISPUTE_INVOICE_SCREEN = "DISPUTE_INVOICE_SCREEN"
export const DISPUTE_PREVIOUS_SCREEN = "DISPUTE_PREVIOUS_SCREEN"
export const DISPUTE_ROW_DATA = "DISPUTE_ROW_DATA"
export const DISPUTE_REVIEW_SCREEN = "DISPUTE_REVIEW_SCREEN"
export const FETCH_ACTIVE_ORDER_DATA_BEGIN = "FETCH_ACTIVE_ORDER_DATA_BEGIN";
export const FETCH_ACTIVE_ORDER_DATA_FAILURE = "FETCH_ACTIVE_ORDER_DATA_FAILURE";
export const FETCH_ACTIVE_ORDER_DATA_SUCCESS = "FETCH_ACTIVE_ORDER_DATA_SUCCESS";

export const FETCH_DISPUTE_ORDER_DATA_BEGIN = "FETCH_DISPUTE_ORDER_DATA_BEGIN";
export const FETCH_DISPUTE_ORDER_DATA_FAILURE = "FETCH_DISPUTE_ORDER_DATA_FAILURE";
export const FETCH_DISPUTE_ORDER_DATA_SUCCESS = "FETCH_DISPUTE_ORDER_DATA_SUCCESS";

export const FETCH_DISPUTE_DETAILS_BEGIN = "FETCH_DISPUTE_DETAILS_BEGIN";
export const FETCH_DISPUTE_DETAILS_FAILURE = "FETCH_DISPUTE_DETAILS_FAILURE";
export const FETCH_DISPUTE_DETAILS_SUCCESS = "FETCH_DISPUTE_DETAILS_SUCCESS";

export const FETCH_CASE_NOTES_BEGIN = "FETCH_CASE_NOTES_BEGIN";
export const FETCH_CASE_NOTES_FAILURE = "FETCH_CASE_NOTES_FAILURE";
export const FETCH_CASE_NOTES_SUCCESS = "FETCH_CASE_NOTES_SUCCESS";

export const FETCH_RESOLVE_BEGIN = "FETCH_RESOLVE_BEGIN";
export const FETCH_RESOLVE_FAILURE = "FETCH_RESOLVE_FAILURE";
export const FETCH_RESOLVE_SUCCESS = "FETCH_RESOLVE_SUCCESS";

export const UPDATE_DISPUTE_BEGIN = "UPDATE_DISPUTE_BEGIN";
export const UPDATE_DISPUTE_FAILURE = "UPDATE_DISPUTE_FAILURE";
export const UPDATE_DISPUTE_SUCCESS = "UPDATE_DISPUTE_SUCCESS";

export const FETCH_HISTORY_BEGIN = "FETCH_HISTORY_BEGIN";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";

export const FETCH_FBO_USER_DATA_BEGIN = "FETCH_FBO_USER_DATA_BEGIN";
export const FETCH_FBO_USER_DATA_FAILURE = "FETCH_FBO_USER_DATA_FAILURE";
export const FETCH_FBO_USER_DATA_SUCCESS = "FETCH_FBO_USER_DATA_SUCCESS";

export const FETCH_COMPLETED_ORDER_JSON_DATA_BEGIN = "FETCH_COMPLETED_ORDER_JSON_DATA_BEGIN";
export const FETCH_COMPLETED_ORDER_JSON_DATA_FAILURE = "FETCH_COMPLETED_ORDER_JSON_DATA_FAILURE";
export const FETCH_COMPLETED_ORDER_JSON_DATA_SUCCESS = "FETCH_COMPLETED_ORDER_JSON_DATA_SUCCESS";
export const FETCH_COMPLETED_ORDER_DATA_BEGIN = "FETCH_COMPLETED_ORDER_DATA_BEGIN";
export const FETCH_COMPLETED_ORDER_DATA_FAILURE = "FETCH_COMPLETED_ORDER_DATA_FAILURE";
export const FETCH_COMPLETED_ORDER_DATA_SUCCESS = "FETCH_COMPLETED_ORDER_DATA_SUCCESS";
export const GET_SEARCH_ORDER_TABLE = "GET_SEARCH_ORDER_TABLE";
export const GET_ORDER_ROW_DATA = "GET_ORDER_ROW_DATA";
export const GET_ORDER_MULTIROW_DATA = "GET_ORDER_MULTIROW_DATA";
export const GET_IS_RESOLVE_DISPUTE = "GET_IS_RESOLVE_DISPUTE";
export const GET_SELECTED_TAB_ORDER = "GET_SELECTED_TAB_ORDER";
export const CLEAR_ALL = 'CLEAR_ALL';
export const GET_ORDER_DATES = "GET_ORDER_DATES";
// statistics
export const FETCH_STATISTICS_DATA_BEGIN = "FETCH_STATISTICS_DATA_BEGIN";
export const FETCH_STATISTICS_DATA_SUCCESS = "FETCH_STATISTICS_DATA_SUCCESS";
export const FETCH_STATISTICS_DATA_FAILURE = "FETCH_STATISTICS_DATA_FAILURE";
export const GET_IS_MINDATE = "GET_IS_MINDATE";
export const GET_IS_MAXDATE = "GET_IS_MAXDATE";
export const IS_CLICK_VIEW_ORDER = "IS_CLICK_VIEW_ORDER";
//fuel price
export const SAVE_SELECTED_FUEL_DATA = "SAVE_SELECTED_FUEL_DATA";

export const SAVE_AUDIT_LOG_DATA_BEGIN = "SAVE_AUDIT_LOG_DATA_BEGIN";
export const SAVE_AUDIT_LOG_DATA_FAILURE = "SAVE_AUDIT_LOG_DATA_FAILURE";
export const SAVE_AUDIT_LOG_DATA_SUCCESS = "SAVE_AUDIT_LOG_DATA_SUCCESS";

export const GET_AUDIT_LOG_DATA_BEGIN = "GET_AUDIT_LOG_DATA_BEGIN";
export const GET_AUDIT_LOG_DATA_FAILURE = "GET_AUDIT_LOG_DATA_FAILURE";
export const GET_AUDIT_LOG_DATA_SUCCESS = "GET_AUDIT_LOG_DATA_SUCCESS";

export const GET_CAT_USER_DATA_BEGIN = "GET_CAT_USER_DATA_BEGIN";
export const GET_CAT_USER_DATA_FAILURE = "GET_CAT_USER_DATA_FAILURE";
export const GET_CAT_USER_DATA_SUCCESS = "GET_CAT_USER_DATA_SUCCESS";

export const GET_SELECTED_TAB_ADMIN = "GET_SELECTED_TAB_ADMIN";
export const FETCH_ADMIN_DATA_BEGIN = "FETCH_ADMIN_DATA_BEGIN";
export const FETCH_ADMIN_DATA_FAILURE = "FETCH_ADMIN_DATA_FAILURE";
export const FETCH_ADMIN_DATA_SUCCESS = "FETCH_ADMIN_DATA_SUCCESS";
export const GET_IS_DEACTIVATE = "GET_IS_DEACTIVATE";
export const GET_INACTIVE_STATUS = "GET_INACTIVE_STATUS"

export const FETCH_OPERATOR_COMPANY_DATA_BEGIN = "FETCH_OPERATOR_COMPANY_DATA_BEGIN";
export const FETCH_OPERATOR_COMPANY_DATA_FAILURE = "FETCH_OPERATOR_COMPANY_DATA_FAILURE";
export const FETCH_OPERATOR_COMPANY_DATA_SUCCESS = "FETCH_OPERATOR_COMPANY_DATA_SUCCESS";

export const GET_SYSTEM_VARIABLES = "GET_SYSTEM_VARIABLES";


